# Generated by Django 4.0.3 on 2022-10-06 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название предмета', max_length=200)),
                ('desc', models.TextField(help_text='Описание предмета', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('user_ip', models.CharField(max_length=20)),
                ('user_agent', models.CharField(max_length=200)),
                ('user_priv', models.CharField(max_length=20)),
                ('online_time', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название теста', max_length=50)),
                ('desc', models.TextField(help_text='Описание теста', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tst.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(max_length=1000)),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Название вопроса', max_length=200)),
                ('right_answer', models.CharField(max_length=1)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tst.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ball', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.questions')),
            ],
        ),
    ]
