# Generated by Django 4.0.3 on 2022-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0002_alter_stats_test_alter_stats_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('ball', models.IntegerField(default=0)),
                ('ans', models.BooleanField(default=False)),
            ],
        ),
    ]
