# Generated by Django 4.0.3 on 2022-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0003_tmptest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptest',
            name='choice',
            field=models.IntegerField(default=0),
        ),
    ]
