# Generated by Django 4.0.3 on 2022-10-26 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0004_tmptest_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='time',
            new_name='timebegin',
        ),
        migrations.AddField(
            model_name='stats',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='timeend',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
    ]
