# Generated by Django 4.0.3 on 2022-10-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0005_rename_time_stats_timebegin_stats_end_stats_timeend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptest',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tst.stats'),
        ),
    ]
